baseurl = "/"
title = "Swapnil Sankla"
theme = "hugo-theme-even"
languagecode = "en"
paginate = 50
canonifyurls = true
disqusShortname = "swapnilsankla"

enableEmoji = true

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[author]                  # essential
  name = "Swapnil Sankla"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "About me"
  weight = 20
  identifier = "categories"
  url = "/about/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2017"            # Site creation time

  # site info (optional)
  logoTitle = "Swapnil Sankla"        # default: the title value
  keywords = ["Swapnil Sankla", "swapnilsankla.me","blogs", "Swift", "Agile"]
  description = "Swapnil Sankla's personal blog site"

  # paginate of archives, tags and categories
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "02-Jan-2006"

  # show word count and read time ?
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # archetypes/default.md。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  autoCollapseToc = true   # Auto expand and collapse toc
  fancybox = true           # see https://github.com/fancyapps/fancybox

 [params.social]
    a-email = "mailto:swapnil.sankla@gmail.com"
    c-twitter = "https://twitter.com/swapnil_sankla"
    e-linkedin = "https://www.linkedin.com/in/swapnil-sankla-30525225/"
    g-github = "https://github.com/SwapnilSankla"

